# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6WcBPF5z9CHqSsP1NUHxtNxhIwAq7y_
"""

import requests
import pandas as pd
from datetime import datetime

# --- 設定區 ---
LINE_ACCESS_TOKEN = "你的_Channel_Access_Token"
USER_ID = "你的_User_ID"

def send_line_push(message):
    url = "https://api.line.me/v2/bot/message/push"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LINE_ACCESS_TOKEN}"
    }
    payload = {
        "to": USER_ID,
        "messages": [{"type": "text", "text": message}]
    }
    res = requests.post(url, headers=headers, json=payload)
    return res.status_code

def get_notice_and_disposition():
    """抓取證交所最新注意及處置股"""
    # 證交所 API 預設抓取最新公布資料
    notice_url = "https://www.twse.com.tw/zh/api/noticeData?response=json"
    punish_url = "https://www.twse.com.tw/zh/api/punishData?response=json"

    msg = "⚠️ 【注意/處置股清單】\n"

    # 1. 注意股
    res_n = requests.get(notice_url).json()
    if res_n.get('stat') == 'OK' and res_n.get('data'):
        msg += "📍注意股:\n"
        for i in res_n['data'][:10]: # 僅列出前10筆避免訊息過長
            msg += f"• {i[1]} {i[2]}\n"
    else:
        msg += "📍注意股: 今日無新增或查無資料\n"

    # 2. 處置股 (處置通常有日期區間)
    res_p = requests.get(punish_url).json()
    if res_p.get('stat') == 'OK' and res_p.get('data'):
        msg += "\n🚫處置股 (處置中):\n"
        for i in res_p['data'][:8]:
            # i[1]代號, i[2]名稱, i[3]處置期間
            msg += f"• {i[1]} {i[2]}\n  ({i[3]})\n"
    else:
        msg += "\n🚫處置股: 目前無處置標的\n"

    return msg

def get_investor_conference():
    """抓取當日法說會 (使用 FinMind 免費 API 較穩定)"""
    today = datetime.now().strftime('%Y-%m-%d')
    # FinMind API 提供較結構化的法說會資料
    url = f"https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockInvestorConference&start_date={today}"

    msg = "\n📅 【今日法說會預告】\n"
    try:
        res = requests.get(url).json()
        if res.get('msg') == 'success' and res.get('data'):
            df = pd.DataFrame(res['data'])
            # 篩選出日期是今天的
            df_today = df[df['date'] == today]
            if not df_today.empty:
                for _, row in df_today.iterrows():
                    msg += f"• {row['stock_id']} {row.get('stock_name', '')}\n"
            else:
                msg += "今日無預定法說會。"
        else:
            msg += "今日無預定法說會。"
    except:
        msg += "法說會資料抓取暫時失效。"

    return msg

def main():
    print(f"[{datetime.now()}] 開始執行爬蟲任務...")

    report = f"💡 台股早報 ({datetime.now().strftime('%m/%d')})\n\n"
    report += get_notice_and_disposition()
    report += get_investor_conference()
    report += "\n祝您投資順利！📈"

    status = send_line_push(report)
    print(f"發送狀態: {status}")

if __name__ == "__main__":
    main()
